'use client';

import {useEffect,useMemo,useState} from 'react';
import {LayoutDashboard,ShoppingBag,UtensilsCrossed,Users,WalletCards,CalendarDays,BarChart3,Settings,Plus,Search,ArrowLeft,Minus,Trash2,CheckCircle2,Pencil,Power,Download,X,Save,UserPlus,ChevronLeft,ChevronRight,RotateCcw,IndianRupee,Receipt} from 'lucide-react';

type Dish={id:string;name:string;category:string;price:number;emoji:string;available:boolean};
type Order={id:string;number:string;items:{name:string;price:number;qty:number}[];subtotal:number;tax:number;total:number;payment:string;createdAt:string;status:string};
type Chef={id:string;name:string;role:string;salary:number;phone:string;present:boolean;active:boolean};
type Expense={id:string;date:string;reason:string;category:string;amount:number;payment:string;person:string};
type Store={dishes:Dish[];orders:Order[];chefs:Chef[];expenses:Expense[];settings:{name:string;phone:string;address:string;gst:boolean;gstPercent:number;opening:string;closing:string;footer:string}};

type Page='Dashboard'|'Orders'|'Menu'|'Chefs'|'Expenses'|'Calendar'|'Reports'|'Settings';
const nav:[[Page,any],...Array<[Page,any]>]=[['Dashboard',LayoutDashboard],['Orders',ShoppingBag],['Menu',UtensilsCrossed],['Chefs',Users],['Expenses',WalletCards],['Calendar',CalendarDays],['Reports',BarChart3],['Settings',Settings]];
const money=(n:number)=>'₹'+Math.round(n||0).toLocaleString('en-IN');
const dateKey=(d=new Date())=>d.toISOString().slice(0,10);
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const seed:Store={
 dishes:[['Veg Steam Momos','Momos',120,'🥟'],['Paneer Momos','Momos',150,'🥟'],['Hakka Noodles','Noodles',140,'🍜'],['Schezwan Fried Rice','Fried Rice',160,'🍚'],['Chilli Paneer','Starters',190,'🥢'],['Manchow Soup','Soups',110,'🍲'],['Paneer Spring Roll','Rolls',130,'🥠'],['Cold Drink','Beverages',60,'🥤']].map((x,i)=>({id:'d'+i,name:x[0],category:x[1],price:x[2],emoji:x[3],available:true})),
 orders:[],
 chefs:[{id:'c1',name:'Ravi Kumar',role:'Head Chef',salary:850,phone:'',present:true,active:true},{id:'c2',name:'Amit Singh',role:'Kitchen Helper',salary:650,phone:'',present:false,active:true}],
 expenses:[],settings:{name:'The Chinese Wala',phone:'',address:'',gst:false,gstPercent:5,opening:'10:30',closing:'23:00',footer:'Thank you for visiting The Chinese Wala!'}
};
function read():Store{try{const x=JSON.parse(localStorage.getItem('cw-store-v3')||'null');return x?{...seed,...x}:seed}catch{return seed}}

export default function Home(){
 const [page,setPage]=useState<Page>('Dashboard');
 const [store,setStore]=useState<Store>(seed); const [ready,setReady]=useState(false); const [notice,setNotice]=useState('');
 const [cart,setCart]=useState<Record<string,number>>({}); const [payment,setPayment]=useState('Cash'); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All');
 const [modal,setModal]=useState<string|null>(null); const [editing,setEditing]=useState<any>(null);
 useEffect(()=>{setStore(read());setReady(true)},[]); useEffect(()=>{if(ready)localStorage.setItem('cw-store-v3',JSON.stringify(store))},[store,ready]);
 const flash=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),2500)};
 const go=(p:Page)=>{setPage(p);setQuery('');setCategory('All')};
 const add=(dish:Dish)=>setCart(c=>({...c,[dish.id]:(c[dish.id]||0)+1}));
 const dec=(dish:Dish)=>setCart(c=>{const n={...c};if((n[dish.id]||0)<=1)delete n[dish.id];else n[dish.id]--;return n});
 const lines=Object.entries(cart).map(([k,q])=>({dish:store.dishes.find(d=>d.id===k)!,qty:q})).filter(x=>x.dish);
 const subtotal=lines.reduce((s,x)=>s+x.dish.price*x.qty,0); const tax=store.settings.gst?Math.round(subtotal*store.settings.gstPercent/100):0; const total=subtotal+tax; const count=lines.reduce((s,x)=>s+x.qty,0);
 const complete=()=>{if(!count)return;const o:Order={id:id(),number:`CW-${String(store.orders.length+1).padStart(4,'0')}`,items:lines.map(x=>({name:x.dish.name,price:x.dish.price,qty:x.qty})),subtotal,tax,total,payment,createdAt:new Date().toISOString(),status:'Completed'};setStore(s=>({...s,orders:[o,...s.orders]}));setCart({});flash(`${o.number} saved successfully`);go('Orders')};
 if(!ready)return <div className="loading">Loading Restaurant OS…</div>;
 return <div className="app"><aside className="sidebar"><div className="brand"><b>🍜 The Chinese Wala</b><small>Restaurant OS</small></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'sel':''} onClick={()=>go(n)}><I size={17}/><span>{n}</span></button>)}</nav><div className="open">● Restaurant open<br/><b>{store.settings.opening} — {store.settings.closing}</b></div><div className="user"><span>A</span><div><b>Owner Admin</b><small>Full access</small></div></div></aside><main><header><div><small>Restaurant management / {page}</small><h1>{page==='Dashboard'?'Good evening, Owner 👋':page}</h1><p>Simple, fast operations for {store.settings.name}.</p></div><div className="headerActions">{page!=='Dashboard'&&<button className="secondary" onClick={()=>go('Dashboard')}><ArrowLeft size={15}/> Dashboard</button>}<button className="primary" onClick={()=>go('Orders')}><Plus size={16}/> New Order</button></div></header>{notice&&<div className="toast"><CheckCircle2 size={17}/>{notice}</div>}
 {page==='Dashboard'&&<Dashboard s={store} go={go}/>} {page==='Orders'&&<Orders s={store} cart={cart} add={add} dec={dec} clear={()=>setCart({})} query={query} setQuery={setQuery} category={category} setCategory={setCategory} payment={payment} setPayment={setPayment} subtotal={subtotal} tax={tax} total={total} count={count} complete={complete}/>} {page==='Menu'&&<Menu s={store} set={setStore} open={(x:any)=>{setEditing(x);setModal('dish')}}/>} {page==='Chefs'&&<Chefs s={store} set={setStore} open={(x:any)=>{setEditing(x);setModal('chef')}} flash={flash}/>} {page==='Expenses'&&<Expenses s={store} set={setStore} open={(x:any)=>{setEditing(x);setModal('expense')}}/>} {page==='Calendar'&&<Calendar s={store}/>} {page==='Reports'&&<Reports s={store}/>} {page==='Settings'&&<SettingsPage s={store} set={setStore} reset={()=>{if(confirm('Reset all local demo data?')){localStorage.removeItem('cw-store-v3');setStore(seed);setCart({});flash('Demo data reset')}}} open={()=>{setEditing(store.settings);setModal('settings')}}/>}
 {modal==='dish'&&<DishModal item={editing} close={()=>setModal(null)} save={(v:Dish)=>{setStore(s=>({...s,dishes:editing?s.dishes.map(x=>x.id===v.id?v:x):[...s.dishes,v]}));setModal(null);flash(editing?'Dish updated':'Dish added')}}/>} {modal==='chef'&&<ChefModal item={editing} close={()=>setModal(null)} save={(v:Chef)=>{setStore(s=>({...s,chefs:editing?s.chefs.map(x=>x.id===v.id?v:x):[...s.chefs,v]}));setModal(null);flash(editing?'Chef updated':'Chef added')}}/>} {modal==='expense'&&<ExpenseModal item={editing} close={()=>setModal(null)} save={(v:Expense)=>{setStore(s=>({...s,expenses:editing?s.expenses.map(x=>x.id===v.id?v:x):[v,...s.expenses]}));setModal(null);flash(editing?'Expense updated':'Expense added')}}/>} {modal==='settings'&&<SettingsModal item={editing} close={()=>setModal(null)} save={(v:any)=>{setStore(s=>({...s,settings:v}));setModal(null);flash('Settings saved')}}/>}</main></div>
}

function Dashboard({s,go}:{s:Store;go:(p:Page)=>void}){const sales=s.orders.reduce((a,o)=>a+o.total,0),exp=s.expenses.reduce((a,e)=>a+e.amount,0),items=s.orders.reduce((a,o)=>a+o.items.reduce((x,i)=>x+i.qty,0),0);return <><div className="stats"><Stat icon={<IndianRupee/>} label="Total sales" value={money(sales)} note={`${s.orders.length} orders`}/><Stat icon={<Receipt/>} label="Orders" value={String(s.orders.length)} note="Completed bills"/><Stat icon={<UtensilsCrossed/>} label="Items sold" value={String(items)} note="Across all orders"/><Stat icon={<WalletCards/>} label="Net collection" value={money(sales-exp)} note={`${money(exp)} expenses`}/></div><div className="cols"><Card title="Sales overview" sub="Last 7 days"><Bars orders={s.orders}/></Card><Card title="Today at a glance" sub={dateKey()}><Rows rows={[["Sales",money(sales)],["Expenses",money(exp)],["Menu items",String(s.dishes.length)],["Active chefs",String(s.chefs.filter(c=>c.active).length)]]}/><div className="net"><span>Estimated net</span><b>{money(sales-exp)}</b></div></Card></div><div className="cols"><Card title="Quick actions" sub="Common restaurant tasks"><div className="quick">{[['New order','Create a POS bill','Orders'],['Manage menu','Add or edit dishes','Menu'],['Chef attendance','Punch in / out','Chefs'],['Add expense','Record spending','Expenses']].map(x=><button key={x[0]} onClick={()=>go(x[2] as Page)}><b>{x[0]}</b><small>{x[1]}</small><ChevronRight size={15}/></button>)}</div></Card><Card title="Chef attendance" sub={`${s.chefs.filter(c=>c.present&&c.active).length} present today`}>{s.chefs.filter(c=>c.active).map(c=><div className="chef" key={c.id}><span>{c.name[0]}</span><div><b>{c.name}</b><small>{c.role} · {money(c.salary)}/day</small></div><em className={c.present?'':'muted'}>● {c.present?'Present':'Absent'}</em></div>)}</Card></div><Card title="Recent orders" sub="Latest bills"><OrderTable orders={s.orders.slice(0,8)}/></Card></>}

function Orders({s,cart,add,dec,clear,query,setQuery,category,setCategory,payment,setPayment,subtotal,tax,total,count,complete}:any){const cats=['All',...Array.from(new Set(s.dishes.map((d:Dish)=>d.category)))];const list=s.dishes.filter((d:Dish)=>d.available&&(category==='All'||d.category===category)&&d.name.toLowerCase().includes(query.toLowerCase()));return <div className="pos"><section className="card orderPanel"><div className="cardHead"><h2>Quick order</h2><small>Tap dishes to add them to the bill</small></div><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search dishes..."/></div><div className="cats">{cats.map(c=><button key={c} className={category===c?'chosen':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="dishes">{list.length?list.map(d=><button className="dish" key={d.id} onClick={()=>add(d)}><span>{d.emoji}</span><b>{d.name}</b><small>{d.category}</small><strong>{money(d.price)}</strong>{cart[d.id]&&<em>{cart[d.id]}</em>}</button>):<div className="emptyMini">No available dishes match your search.</div>}</div></section><section className="bill"><div className="billHead"><div><h2>Current order</h2><small>{count} items</small></div>{count>0&&<button className="clearBtn" onClick={clear}><Trash2 size={13}/> Clear</button>}</div>{Object.entries(cart).map(([k,q]:any)=>{const d=s.dishes.find((x:Dish)=>x.id===k);return d?<div className="line" key={k}><span><b>{d.name}</b><small>{money(d.price)} each</small></span><div className="qty"><button onClick={()=>dec(d)}><Minus size={12}/></button><b>{q}</b><button onClick={()=>add(d)}><Plus size={12}/></button></div><strong>{money(d.price*q)}</strong></div>:null})}<div className="billFoot"><Rows rows={[["Subtotal",money(subtotal)],["Discount","₹0"],["Tax",money(tax)]]}/><div className="total"><span>Total</span><b>{money(total)}</b></div><div className="payments">{['Cash','UPI','Card','Credit'].map(p=><button key={p} className={payment===p?'payChosen':''} onClick={()=>setPayment(p)}>{p}</button>)}</div><button className="checkout" disabled={!count} onClick={complete}>Complete order · {money(total)}</button></div></section></div>}

function Menu({s,set,open}:{s:Store;set:React.Dispatch<React.SetStateAction<Store>>;open:(x:any)=>void}){const [q,setQ]=useState('');const [cat,setCat]=useState('All');const cats=['All',...Array.from(new Set(s.dishes.map(d=>d.category)))];const list=s.dishes.filter(d=>(cat==='All'||d.category===cat)&&d.name.toLowerCase().includes(q.toLowerCase()));return <Card title="Menu management" sub={`${s.dishes.length} dishes`}><div className="toolbar"><div className="search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search menu..."/></div><button className="primary" onClick={()=>open(null)}><Plus size={15}/> Add dish</button></div><div className="cats">{cats.map(c=><button key={c} className={cat===c?'chosen':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="menuGrid">{list.map(d=><div className="menuItem" key={d.id}><span>{d.emoji}</span><div><b>{d.name}</b><small>{d.category} · {money(d.price)}</small><em className={d.available?'available':'unavailable'}>{d.available?'Available':'Unavailable'}</em></div><div className="itemActions"><button onClick={()=>open(d)}><Pencil size={14}/></button><button onClick={()=>set(x=>({...x,dishes:x.dishes.map(y=>y.id===d.id?{...y,available:!y.available}:y)}))}><Power size={14}/></button><button onClick={()=>{if(confirm('Delete this dish?'))set(x=>({...x,dishes:x.dishes.filter(y=>y.id!==d.id)}))}}><Trash2 size={14}/></button></div></div>)}</div></Card>}

function Chefs({s,set,open,flash}:{s:Store;set:React.Dispatch<React.SetStateAction<Store>>;open:(x:any)=>void;flash:(x:string)=>void}){return <><div className="pageToolbar"><div><h2>Chefs & attendance</h2><small>Manage staff and daily attendance.</small></div><button className="primary" onClick={()=>open(null)}><UserPlus size={15}/> Add chef</button></div><div className="chefGrid">{s.chefs.map(c=><Card key={c.id} title={c.name} sub={c.role}><div className="chefTop"><span>{c.name[0]}</span><div><b>{c.role}</b><small>{c.phone||'No phone'} · {money(c.salary)}/day</small></div><button className={c.present?'statusOn':'statusOff'} onClick={()=>{set(x=>({...x,chefs:x.chefs.map(y=>y.id===c.id?{...y,present:!y.present}:y)}));flash('Attendance updated')}}>{c.present?'Present':'Absent'}</button></div><div className="cardActions"><button className="secondary" onClick={()=>open(c)}><Pencil size={13}/> Edit</button><button className="secondary" onClick={()=>set(x=>({...x,chefs:x.chefs.map(y=>y.id===c.id?{...y,active:!y.active}:y)}))}><Power size={13}/> {c.active?'Deactivate':'Activate'}</button></div></Card>)}</div></>}

function Expenses({s,set,open}:{s:Store;set:React.Dispatch<React.SetStateAction<Store>>;open:(x:any)=>void}){const total=s.expenses.reduce((a,e)=>a+e.amount,0);return <><div className="pageToolbar"><div><h2>Expenses</h2><small>Track grocery, utility, repair and other spending.</small></div><button className="primary" onClick={()=>open(null)}><Plus size={15}/> Add expense</button></div><div className="stats"><Stat icon={<IndianRupee/>} label="Total expenses" value={money(total)} note={`${s.expenses.length} entries`}/><Stat icon={<Receipt/>} label="Today" value={money(s.expenses.filter(e=>e.date===dateKey()).reduce((a,e)=>a+e.amount,0))} note="Today's spend"/><Stat icon={<WalletCards/>} label="Average" value={money(s.expenses.length?total/s.expenses.length:0)} note="Per entry"/><Stat icon={<BarChart3/>} label="Categories" value={String(new Set(s.expenses.map(e=>e.category)).size)} note="Used categories"/></div><Card title="Expense ledger" sub="Newest first"><div className="table"><div className="tr headRow"><span>Date</span><span>Reason</span><span>Category</span><span>Payment</span><span>Amount</span><span>Actions</span></div>{s.expenses.length?s.expenses.map(e=><div className="tr" key={e.id}><span>{e.date}</span><span>{e.reason}</span><span>{e.category}</span><span>{e.payment}</span><span>{money(e.amount)}</span><span className="rowButtons"><button onClick={()=>open(e)}><Pencil size={13}/></button><button onClick={()=>{if(confirm('Delete this expense?'))set(x=>({...x,expenses:x.expenses.filter(y=>y.id!==e.id)}))}}><Trash2 size={13}/></button></span></div>):<div className="emptyMini">No expenses recorded yet.</div>}</div></Card></>}

function Calendar({s}:{s:Store}){const [cursor,setCursor]=useState(new Date());const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();return <Card title="Operations calendar" sub="Orders and expenses by date"><div className="calendarHead"><button className="secondary" onClick={()=>setCursor(new Date())}>Today</button><div><button className="iconBtn" onClick={()=>setCursor(new Date(y,m-1,1))}><ChevronLeft size={16}/></button><b>{cursor.toLocaleString('en-US',{month:'long',year:'numeric'})}</b><button className="iconBtn" onClick={()=>setCursor(new Date(y,m+1,1))}><ChevronRight size={16}/></button></div></div><div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar">{Array.from({length:first+days},(_,i)=>{if(i<first)return <div className="day blank" key={i}/>;const d=i-first+1,k=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,o=s.orders.filter(x=>x.createdAt.slice(0,10)===k).length,e=s.expenses.filter(x=>x.date===k).length;return <div className={`day ${k===dateKey()?'today':''}`} key={k}><b>{d}</b>{o>0&&<small>{o} order{o>1?'s':''}</small>}{e>0&&<small>{e} expense{e>1?'s':''}</small>}</div>})}</div></Card>}

function Reports({s}:{s:Store}){const [range,setRange]=useState(30);const cut=Date.now()-range*86400000;const orders=s.orders.filter(o=>new Date(o.createdAt).getTime()>=cut),sales=orders.reduce((a,o)=>a+o.total,0),exp=s.expenses.filter(e=>new Date(e.date).getTime()>=cut).reduce((a,e)=>a+e.amount,0);const top=new Map<string,number>();orders.forEach(o=>o.items.forEach(i=>top.set(i.name,(top.get(i.name)||0)+i.qty)));const csv=()=>{const rows=[['Order','Date','Payment','Items','Total'],...orders.map(o=>[o.number,o.createdAt.slice(0,10),o.payment,String(o.items.reduce((a,i)=>a+i.qty,0)),String(o.total)])];const blob=new Blob([rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`orders-${dateKey()}.csv`;a.click();URL.revokeObjectURL(a.href)};return <><div className="pageToolbar"><div><h2>Reports</h2><small>Sales, expenses and product performance.</small></div><div className="headerActions"><select className="select" value={range} onChange={e=>setRange(+e.target.value)}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><button className="primary" onClick={csv}><Download size={15}/> Export CSV</button></div></div><div className="stats"><Stat icon={<IndianRupee/>} label="Sales" value={money(sales)} note={`${orders.length} orders`}/><Stat icon={<WalletCards/>} label="Expenses" value={money(exp)} note="Recorded spend"/><Stat icon={<Receipt/>} label="Net" value={money(sales-exp)} note="Sales minus expenses"/><Stat icon={<ShoppingBag/>} label="Avg order" value={money(orders.length?sales/orders.length:0)} note="Average bill"/></div><div className="cols"><Card title="Top dishes" sub="Units sold"><div className="rankList">{[...top.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6).map((x,i)=><div className="rank" key={x[0]}><span>{i+1}</span><b>{x[0]}</b><strong>{x[1]}</strong></div>)}</div></Card><Card title="Payment mix" sub="Orders by method"><Rows rows={['Cash','UPI','Card','Credit'].map(p=>[p,`${orders.filter(o=>o.payment===p).length} orders`])}/></Card></div><Card title="Order report" sub="Selected period"><OrderTable orders={orders}/></Card></>}

function SettingsPage({s,open,reset}:{s:Store;set:React.Dispatch<React.SetStateAction<Store>>;open:()=>void;reset:()=>void}){return <><div className="pageToolbar"><div><h2>Settings</h2><small>Restaurant profile and billing defaults.</small></div><button className="primary" onClick={open}><Settings size={15}/> Edit settings</button></div><div className="settingsGrid"><Card title="Business profile" sub="Restaurant information"><Rows rows={[["Name",s.settings.name],["Phone",s.settings.phone||'Not set'],["Address",s.settings.address||'Not set'],["Hours",`${s.settings.opening} — ${s.settings.closing}`]]}/></Card><Card title="Billing" sub="POS defaults"><Rows rows={[["GST",s.settings.gst?'Enabled':'Disabled'],["GST rate",s.settings.gst?`${s.settings.gstPercent}%`:'—'],["Currency",'INR (₹)'],["Receipt footer",s.settings.footer]]}/></Card></div><Card title="Local data" sub="This demo works without an auth session"><p className="settingsNote">The POS, menu, staff and expense modules persist in this browser. Supabase can be connected later when authentication is enabled.</p><button className="secondary" onClick={reset}><RotateCcw size={14}/> Reset demo data</button></Card></>}

function Bars({orders}:{orders:Order[]}){const ds=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d}),vals=ds.map(d=>orders.filter(o=>o.createdAt.slice(0,10)===d.toISOString().slice(0,10)).reduce((a,o)=>a+o.total,0)),max=Math.max(...vals,1);return <div className="chart">{vals.map((v,i)=><div className="bar" style={{height:Math.max(8,v/max*100)+'%'}} key={i}><i></i><small>{ds[i].toLocaleDateString('en-IN',{weekday:'short'}).slice(0,1)}</small></div>)}</div>}
function OrderTable({orders}:{orders:Order[]}){return <div className="table">{orders.length?orders.map(o=><div className="tr" key={o.id}><span>{o.number}</span><span>{o.createdAt.slice(0,10)}</span><span>{o.items.reduce((a,i)=>a+i.qty,0)} items</span><span>{o.payment}</span><span>{money(o.total)}</span><span className="ok">{o.status}</span></div>):<div className="emptyMini">No orders yet. Click New Order to create the first bill.</div>}</div>}
function Stat({icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="stat"><div className="ico">{icon}</div><small>{label}</small><strong>{value}</strong><em>{note}</em></div>}
function Card({title,sub,children}:{title:string;sub?:string;children:React.ReactNode}){return <section className="card"><div className="cardHead"><h2>{title}</h2>{sub&&<small>{sub}</small>}</div>{children}</section>}
function Rows({rows}:{rows:(string|number)[][]}){return <div>{rows.map((r,i)=><div className="row" key={String(r[0])+i}><span>{r[0]}</span><b>{r[1]}</b></div>)}</div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modalHead"><h2>{title}</h2><button onClick={close}><X size={17}/></button></div>{children}</div></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <label className="field"><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
function DishModal({item,close,save}:{item:Dish|null;close:()=>void;save:(v:Dish)=>void}){const [v,setV]=useState<Dish>(item||{id:id(),name:'',category:'Momos',price:0,emoji:'🍜',available:true});return <Modal title={item?'Edit dish':'Add dish'} close={close}><div className="formGrid"><Field label="Name" value={v.name} onChange={x=>setV({...v,name:x})}/><Field label="Price" value={v.price} onChange={x=>setV({...v,price:+x||0})} type="number"/><Field label="Category" value={v.category} onChange={x=>setV({...v,category:x})}/><Field label="Emoji" value={v.emoji} onChange={x=>setV({...v,emoji:x})}/></div><label className="check"><input type="checkbox" checked={v.available} onChange={e=>setV({...v,available:e.target.checked})}/> Available for ordering</label><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>v.name.trim()&&save(v)}><Save size={14}/> Save</button></div></Modal>}
function ChefModal({item,close,save}:{item:Chef|null;close:()=>void;save:(v:Chef)=>void}){const [v,setV]=useState<Chef>(item||{id:id(),name:'',role:'Kitchen Staff',salary:0,phone:'',present:false,active:true});return <Modal title={item?'Edit chef':'Add chef'} close={close}><div className="formGrid"><Field label="Name" value={v.name} onChange={x=>setV({...v,name:x})}/><Field label="Role" value={v.role} onChange={x=>setV({...v,role:x})}/><Field label="Daily salary" value={v.salary} onChange={x=>setV({...v,salary:+x||0})} type="number"/><Field label="Phone" value={v.phone} onChange={x=>setV({...v,phone:x})}/></div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>v.name.trim()&&save(v)}><Save size={14}/> Save</button></div></Modal>}
function ExpenseModal({item,close,save}:{item:Expense|null;close:()=>void;save:(v:Expense)=>void}){const [v,setV]=useState<Expense>(item||{id:id(),date:dateKey(),reason:'',category:'Groceries',amount:0,payment:'Cash',person:''});return <Modal title={item?'Edit expense':'Add expense'} close={close}><div className="formGrid"><Field label="Date" value={v.date} onChange={x=>setV({...v,date:x})} type="date"/><Field label="Amount" value={v.amount} onChange={x=>setV({...v,amount:+x||0})} type="number"/><Field label="Reason" value={v.reason} onChange={x=>setV({...v,reason:x})}/><Field label="Category" value={v.category} onChange={x=>setV({...v,category:x})}/><Field label="Payment" value={v.payment} onChange={x=>setV({...v,payment:x})}/><Field label="Person/vendor" value={v.person} onChange={x=>setV({...v,person:x})}/></div><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>v.reason.trim()&&save(v)}><Save size={14}/> Save</button></div></Modal>}
function SettingsModal({item,close,save}:{item:any;close:()=>void;save:(v:any)=>void}){const [v,setV]=useState(item);return <Modal title="Restaurant settings" close={close}><div className="formGrid"><Field label="Restaurant name" value={v.name} onChange={x=>setV({...v,name:x})}/><Field label="Phone" value={v.phone} onChange={x=>setV({...v,phone:x})}/><Field label="Opening" value={v.opening} onChange={x=>setV({...v,opening:x})} type="time"/><Field label="Closing" value={v.closing} onChange={x=>setV({...v,closing:x})} type="time"/><Field label="GST %" value={v.gstPercent} onChange={x=>setV({...v,gstPercent:+x||0})} type="number"/><Field label="Receipt footer" value={v.footer} onChange={x=>setV({...v,footer:x})}/></div><label className="field"><span>Address</span><textarea value={v.address||''} onChange={e=>setV({...v,address:e.target.value})}/></label><label className="check"><input type="checkbox" checked={v.gst} onChange={e=>setV({...v,gst:e.target.checked})}/> Apply GST to new orders</label><div className="modalActions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>save(v)}><Save size={14}/> Save</button></div></Modal>}
