'use client';

import {useEffect,useMemo,useState} from 'react';
import {LayoutDashboard,ShoppingBag,UtensilsCrossed,Users,WalletCards,CalendarDays,BarChart3,Settings,Plus,Search,ChevronRight,IndianRupee,Receipt,ArrowLeft,Minus,Trash2,CheckCircle2} from 'lucide-react';

const cats=['All','Momos','Noodles','Fried Rice','Starters','Soups','Rolls','Beverages','Combos'];
const dishes=[['Veg Steam Momos','Momos',120,'🥟'],['Paneer Momos','Momos',150,'🥟'],['Hakka Noodles','Noodles',140,'🍜'],['Schezwan Fried Rice','Fried Rice',160,'🍚'],['Chilli Paneer','Starters',190,'🥢'],['Manchow Soup','Soups',110,'🍲'],['Paneer Spring Roll','Rolls',130,'🥠'],['Cold Drink','Beverages',60,'🥤']] as const;
const nav=[['Dashboard',LayoutDashboard],['Orders',ShoppingBag],['Menu',UtensilsCrossed],['Chefs',Users],['Expenses',WalletCards],['Calendar',CalendarDays],['Reports',BarChart3],['Settings',Settings]] as const;
const money=(n:number)=>'₹'+n.toLocaleString('en-IN');
type Cart=Record<string,number>;
type SavedOrder={id:string,total:number,count:number,payment:string,createdAt:string,status:string};

export default function Home(){
 const[page,setPage]=useState('Dashboard');
 const[cat,setCat]=useState('All'); const[q,setQ]=useState(''); const[cart,setCart]=useState<Cart>({});
 const[payment,setPayment]=useState('Cash'); const[orders,setOrders]=useState<SavedOrder[]>([]); const[notice,setNotice]=useState('');
 useEffect(()=>{try{setOrders(JSON.parse(localStorage.getItem('cw-orders')||'[]'))}catch{setOrders([])}},[]);
 useEffect(()=>{if(orders.length)localStorage.setItem('cw-orders',JSON.stringify(orders))},[orders]);
 const filtered=dishes.filter(d=>(cat==='All'||d[1]===cat)&&d[0].toLowerCase().includes(q.toLowerCase()));
 const total=useMemo(()=>dishes.reduce((s,d)=>s+(cart[d[0]]||0)*d[2],0),[cart]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0);
 const add=(name:string)=>setCart(x=>({...x,[name]:(x[name]||0)+1}));
 const remove=(name:string)=>setCart(x=>{const next={...x}; const n=(next[name]||0)-1; if(n<=0)delete next[name]; else next[name]=n; return next});
 const clear=()=>setCart({});
 const completeOrder=()=>{if(!count)return; const id=`CW-${String(orders.length+1).padStart(4,'0')}`; const order={id,total,count,payment,createdAt:new Date().toISOString(),status:'Completed'}; setOrders(x=>[order,...x]); clear(); setNotice(`${id} saved successfully`); setTimeout(()=>setNotice(''),2800)};
 return <div className="app">
  <aside className="sidebar"><div className="brand"><b>🍜 The Chinese Wala</b><small>Restaurant OS</small></div><nav>{nav.map(([n,I])=><button className={page===n?'sel':''} onClick={()=>setPage(n)} key={n}><I size={17}/><span>{n}</span></button>)}</nav><div className="open">● Restaurant open<br/><b>10:30 AM — 11 PM</b></div><div className="user"><span>A</span><div><b>Owner Admin</b><small>Full access</small></div></div></aside>
  <main><header><div><small>Restaurant management / {page}</small><h1>{page==='Dashboard'?'Good evening, Owner 👋':page}</h1><p>Simple, fast operations for The Chinese Wala.</p></div><div className="headerActions">{page!=='Dashboard'&&<button className="secondary" onClick={()=>setPage('Dashboard')}><ArrowLeft size={15}/> Dashboard</button>}<button className="primary" onClick={()=>setPage('Orders')}><Plus size={16}/> New Order</button></div></header>
   {notice&&<div className="toast"><CheckCircle2 size={17}/>{notice}</div>}
   {page==='Dashboard'?<Dashboard setPage={setPage} orders={orders}/>:page==='Orders'?<Orders filtered={filtered} cat={cat} setCat={setCat} q={q} setQ={setQ} cart={cart} add={add} remove={remove} total={total} count={count} payment={payment} setPayment={setPayment} completeOrder={completeOrder} clear={clear}/>:<div className="empty"><div>{page==='Menu'?'🍜':page==='Chefs'?'👨‍🍳':page==='Expenses'?'🧾':page==='Calendar'?'📅':page==='Reports'?'📊':'⚙️'}</div><h2>{page}</h2><p>This module is next in the build. Your navigation is working, and you can return to the dashboard at any time.</p><button className="primary" onClick={()=>setPage('Dashboard')}>Back to dashboard</button></div>}
  </main>
 </div>
}

function Dashboard({setPage,orders}:{setPage:(p:string)=>void,orders:SavedOrder[]}){const sales=orders.filter(o=>o.status==='Completed').reduce((s,o)=>s+o.total,0);return <><section className="stats"><Stat icon={<IndianRupee/>} label="Today's sales" value={money(sales||18450)} note={orders.length?`${orders.length} saved orders`:'+12.4% vs yesterday'}/><Stat icon={<Receipt/>} label="Orders" value={String(orders.length||86)} note="Completed today"/><Stat icon={<UtensilsCrossed/>} label="Items sold" value={String(orders.reduce((s,o)=>s+o.count,0)||214)} note="Top dish: Momos"/><Stat icon={<WalletCards/>} label="Net collection" value={money(sales||12680)} note="After expenses & payouts"/></section><div className="cols"><Card title="Sales overview" sub="Last 7 days"><div className="chart">{[42,58,46,72,64,88,76].map((h,i)=><div className="bar" style={{height:h+'%'}} key={i}><i></i><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></Card><Card title="Today at a glance" sub="30 Sep 2026"><Rows rows={[["Cash sales","₹7,200"],["UPI / Online","₹9,850"],["Pending credit","₹1,400"],["Business expenses","−₹2,150"],["Chef advances","−₹850"]]}/><div className="net"><span>Estimated net</span><b>₹12,680</b></div></Card></div><div className="cols"><Card title="Quick actions" sub="Common restaurant tasks"><div className="quick">{[['New order','Create a POS bill','Orders'],['Chef attendance','Punch in / out','Chefs'],['Add expense','Record grocery spend','Expenses'],['Pay salary','Settle chef payout','Chefs']].map(x=><button key={x[0]} onClick={()=>setPage(x[2])}><b>{x[0]}</b><small>{x[1]}</small><ChevronRight size={15}/></button>)}</div></Card><Card title="Chef attendance" sub="1 of 2 currently present"><div className="chef"><span>R</span><div><b>Ravi Kumar</b><small>Head Chef · ₹850/day</small></div><em>● Punched in<br/><small>10:12 AM</small></em></div><div className="chef"><span>A</span><div><b>Amit Singh</b><small>Kitchen Helper</small></div><em className="muted">● Absent</em></div></Card></div><Card title="Recent orders" sub="Latest bills"><div className="table">{(orders.length?orders:[{id:'#CW-0086',count:3,payment:'UPI',total:520,status:'Completed'},{id:'#CW-0085',count:5,payment:'Cash',total:840,status:'Completed'},{id:'#CW-0084',count:2,payment:'Credit',total:320,status:'Pending'}]).slice(0,6).map((r:any)=><div className="tr" key={r.id}><span>{r.id}</span><span>Today</span><span>{r.count} items</span><span>{r.payment}</span><span>{money(r.total)}</span><span className={r.status==='Completed'?'ok':'warn'}>{r.status}</span></div>)}</div></Card></>}

function Orders({filtered,cat,setCat,q,setQ,cart,add,remove,total,count,payment,setPayment,completeOrder,clear}:any){return <div className="pos"><section className="card orderPanel"><div className="cardHead"><div><h2>Quick order</h2><small>Tap dishes to add them to the bill</small></div></div><div className="search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search dishes..."/></div><div className="cats">{cats.map(c=><button className={cat===c?'chosen':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="dishes">{filtered.map((d:any)=><button className="dish" key={d[0]} onClick={()=>add(d[0])}><span>{d[3]}</span><b>{d[0]}</b><small>{d[1]}</small><strong>{money(d[2])}</strong>{cart[d[0]]&&<em>{cart[d[0]]}</em>}</button>)}</div></section><section className="bill"><div className="billHead"><div><h2>Current order</h2><small>{count} items</small></div>{count>0&&<button className="clearBtn" onClick={clear}><Trash2 size={13}/> Clear</button>}</div>{Object.entries(cart).map(([name,n]:any)=>{const dish=dishes.find(d=>d[0]===name)!;return <div className="line" key={name}><span><b>{name}</b><small>{money(dish[2])} each</small></span><div className="qty"><button onClick={()=>remove(name)}><Minus size={12}/></button><b>{n}</b><button onClick={()=>add(name)}><Plus size={12}/></button></div><strong>{money(n*dish[2])}</strong></div>})}<div className="billFoot"><Rows rows={[["Subtotal",money(total)],["Discount","₹0"],["Tax","₹0"]]}/><div className="total"><span>Total</span><b>{money(total)}</b></div><div className="payments">{['Cash','UPI','Card','Credit'].map(p=><button className={payment===p?'payChosen':''} onClick={()=>setPayment(p)} key={p}>{p}</button>)}</div><button className="checkout" disabled={!count} onClick={completeOrder}>Complete order · {money(total)}</button></div></section></div>}
function Stat({icon,label,value,note}:any){return <div className="stat"><div className="ico">{icon}</div><small>{label}</small><strong>{value}</strong><em>{note}</em></div>};function Card({title,sub,children}:any){return <section className="card"><div className="cardHead"><div><h2>{title}</h2><small>{sub}</small></div></div>{children}</section>};function Rows({rows}:any){return <div>{rows.map((r:any)=><div className="row" key={r[0]}><span>{r[0]}</span><b>{r[1]}</b></div>)}</div>}
